sudo: false
language: node_js
node_js:
- '0.12'
notifications:
  email:
  - ilya@pukhalski.com
env:
  global:
  - GH_OAUTH_TOKEN:
    - secure: mJ0gi2Z+XZqOZ2BdwxDOP/hyJmpCDNi+/5OBejzbnMoF7gmI29Jki9mmiNMAzsLSttWMKLxgM4boX0Be1kXWnZ/qXYDpPUpRh0BYZSRCA4Qzj2w6B9AzJvfsuyrRUVjo0Vi3ca0JWcAeYMNDV8SGaKFNsPnp6XxlPKPt5zRpB8AzytnZaXnmOvlzTA+tWI5umQsxDTghkbH1pbCRZfKvbpRdmbO8FVoKPSgF3sciFY8WaQYyDhgWZ22+Z5hBiNIuzCXgzY/JVuoHK5aYtd6xAg/Pwv2PV7e/MGGeW3yBtoae/MIshT8P3tp6O+PE4oRKky6J/us8Kg54trOKfnI3goZXiiHi3cwQSM15eIIeRrTsPB42lLUdYZlj2lrTkHtt48d9bbpIqA6O+tdBPaKp6qbn/JtGX+mOZWmYzg23ki/qYLaTfl4Bn8qRdb7fDJCZabcdzvJ7Tq5ZtJ1dAHMJY13GddD/O/CMZG/i60mMzIL41VbjDyd4qLmmqhrSGhAH4U+FKX4M9K2Q3K0miIlVUwf599xoAcmuufX63kBYwXcm6dXKbua3QYuSzPMIXlKyHmKJGiVjZcFjSsVyv/ioiNQSU55wPyI3BiBnAJjOn7pldkOtuVEJHZenViFA8T7Z7yDUH9EwoAh9ChfXWsX+Tri8Q5nagt8IY6MvTBixA4k=
  - GH_OWNER: todoflux
  - GH_PROJECT_NAME: todoflux
  - CHROME_PATH: /home/travis/build/todoflux/todoflux/chrome-linux/chrome
  - secure: CkAAoHuogZs037Jsh+TWq7HBrrL6l0XCEGHL8Pfr2Umej8bxIJgI3REc5Y9lHIfHWgFP7lzQGo1CvZUg2K4WD8AkeSqUptB/FNQxkRtCXk2fRrDAgiv65KYJLJ99SpR4vbvFii89OEAfArzV0P1ukpW6kuRoggHqvBC4NHWEhfcYfENtHk9FgPF4RYIpn7ayduuJ7fZvgen28A5McPEyG+6yxxKy+XUhBVisjka4qqSIddUWfDBAHOo0PujegepUrLkwcMMiWte+2P2OtzSWK3hgInMZP3PJOjnG1TNcyUtJngCVjdFE/5hYM2ppnTvX4u6tOsF6+WBMOW0Awp4k7pkYiS7jxbDhB9chTXHix/qnKH0RYGISt96mxUTTpRHvZdssgTwmozg8u4/0UG9Pf/03XKusKWwE0YbQ2bJXI5uwDmTHyg97UL5C0USKnz3zz7Ltmq52Nwi1jzeCV5gQT3yqqpjhchptkNR8NlyCB1t2/JB7XiYqXbNPMFfBsWvLBa0Vr/6g6cgCRRlCRgQo2lnFK/HWtuQl1jEt1Vn9q2whU20TxD1yasBU6YVkZosggYf7SGnshFF2tqBMGW9xsaYZwVxBAYBweItZNxHy62gB9+W/86BGO5EtGDzWpXzunKZFxW3G4ayMaX8PdLzlhQavA4/PTw3/lp8yLWJb5yY=
  - secure: jCPrPpZN8l23bLFQru1Ca05UO6B+zEA03r9C2Ohj2amq15HrShQeFWQAf7air+SqOR90ZEgFwagZsoUAUeA08oayXAn9jfpoggXS5a5BJY1NcK0s2XxgFvIQuoIJ+EnxjhFoGDMnP3HSaWQBDXdgRoXFOQH5tPF2tS4ap281xA/yzcVL9H3NcpAd96dCX8OkPVo31qBDTJ7z+EIVzR+W9qpzQ7V75NPZ5yLUZTjgqdupR+DaHoMvdtY0AOKciF5RTSmf/9PAa2me3ZJ4SXABzvEHAALVCjc/2CvTrVWPdv4NQTeKb13N2yWKH2TaiWzwW4NIya0ITmarvuVAUtVchDO2G8ZY4HVUM0RlQvXQ1l0+6Opni2zxoU5MmhPnuyK+/F75rcAk+zGWOeIMFEJ2oEYphGa8PlvO6OBzWB/WSPaczcnBjzk2JPUzBCwk2lhLvNc6ANbTtNWBdDd3hBQKwgdICaAP3IQcdNXACekQi5It5wEGdCEqtz5nUGE0ODgUr3La8EAZb9IXVTja5ZoqM/rINt11jPZFA09gn3SmvuFKAw+3EpS4r1NepDM9BDMbcWgM7ImeL/kWdsI9Bw+o/i42l96rvgdw4gEQyOwIwwzzepqypeH93dJoiWedGpAt9JVcNL/RbRXcCxgPw0jxFNJdTPNpwFKxnO+yUcPjUXk=
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip
  chrome.zip
- curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip
  && unzip chromedriver.zip
before_script:
- npm install -g gulp
- python -m SimpleHTTPServer > /dev/null 2>&1 &
- sleep 2
script:
- gulp
- ./test-runner.sh
